### ISSUE TITLE
license missing :)

### ISSUE THREAD

**Issue by IzzySoft** [aeharding/capacitor-stash-media#1]
Looks like you forgot to set the license on the repo. Luckily, your `package.json` gives a clue, so I assume it should be MIT. Could you add the license to the repo, too – to avoid the ambiguosity caused by the "ISC" being declared in `example/package.json`? :wink: Thanks!

**Comment by aeharding** [comment]
Apologies - it's been added! :)

**Comment by IzzySoft** [comment]
Thanks a lot!
